import type { CatalogMechanicalVisualAsset } from './mechanicalVisualAssets';

// Generated by scripts/catalog/import-objective-edrawings-assets.mjs.
// The app renders these browser-loadable eDrawing mesh/line assets; STEP and
// SolidWorks URLs in the catalog remain source CAD.
export const GENERATED_MECHANICAL_VISUAL_ASSETS: Record<string, CatalogMechanicalVisualAsset> = {
    "thorlabs:TL10X-2P": {
        "partId": "thorlabs:TL10X-2P",
        "sku": "TL10X-2P",
        "format": "edrawings-json",
        "url": "/catalog/mechanical/objectives/tl10x-2p.edrawings.json",
        "sourceUrl": "https://media.thorlabs.com/globalassets/items/t/tl/tl1/tl10x-2p/ttn142896-e0w.html?v=0501060152",
        "units": "mm",
        "generatedAt": "2026-05-19T22:26:46.435Z"
    },
    "thorlabs:TL15X-2P": {
        "partId": "thorlabs:TL15X-2P",
        "sku": "TL15X-2P",
        "format": "edrawings-json",
        "url": "/catalog/mechanical/objectives/tl15x-2p.edrawings.json",
        "sourceUrl": "https://media.thorlabs.com/globalassets/items/t/tl/tl1/tl15x-2p/stn057599-e0w.html?v=0116031845",
        "units": "mm",
        "generatedAt": "2026-05-19T22:39:20.608Z"
    },
    "thorlabs:TL28X-MP": {
        "partId": "thorlabs:TL28X-MP",
        "sku": "TL28X-MP",
        "format": "edrawings-json",
        "url": "/catalog/mechanical/objectives/tl28x-mp.edrawings.json",
        "sourceUrl": "https://media.thorlabs.com/globalassets/items/t/tl/tl2/tl28x-mp/tl28x-mp-e0w.html?v=0116031846",
        "units": "mm",
        "generatedAt": "2026-05-19T22:31:51.261Z"
    },
    "thorlabs:TL2X-SAP": {
        "partId": "thorlabs:TL2X-SAP",
        "sku": "TL2X-SAP",
        "format": "edrawings-json",
        "url": "/catalog/mechanical/objectives/tl2x-sap.edrawings.json",
        "sourceUrl": "https://media.thorlabs.com/globalassets/items/t/tl/tl2/tl2x-sap/ttn108158-e0w.html?v=0501060157",
        "units": "mm",
        "generatedAt": "2026-05-19T22:32:00.416Z"
    }
};
