import React, { useState, useMemo, useEffect, useRef } from 'react';
import { useAtom } from 'jotai';
import {
    GraduationCap,
    MousePointer2,
    Info,
    ChevronRight,
    ExternalLink,
} from 'lucide-react';
import { appRouteAtom, loadPresetAtom, PresetName } from '../state/store';
import { useIsMobile } from './useIsMobile';

// ── Palette (matches Sidebar brand mark + app accents) ─────────────────
const ACCENT_CYAN = '#64ffda';
const ACCENT_BLUE = '#007fff';
const TEXT_PRIMARY = '#eaf6ff';
const TEXT_DIM = '#8a96a4';

// ── Tips ────────────────────────────────────────────────────────────────
// These should mostly be about controls the user might have missed
const TIPS: string[] = [
    'Hold Alt while dragging to snap to nearby optical axes.',
    'Press Ctrl+Z to undo any change.',
    'Toggle the lock icon top-right to hide the editing panels for a clean optical-table view.',
    'Animate properties, such as mirror angles or stage positions to make scans.',
    'Use the ruler tool to measure distances and verify focal-length sums.',
    'Drop a viewing card on the table to see a wave reconstruction of a beam profile.',
    'Right-click, or Long press on mobile opens a context menu.',
];

// ── Preset metadata + diagrams ─────────────────────────────────────────
type Category = 'Microscopes' | 'Optics & Physics' | 'Showcase' | 'Papers';

interface PresetCardData {
    preset: PresetName;
    title: string;
    category: Category;
    tagline: string;
    accent: string;
    /** Filename in public/presets/. Swap the file to update the screenshot. */
    image: string;
}

/** Resolve a public-folder asset under Vite's configured base path. */
const PRESET_IMAGE_URL = (file: string) => `${import.meta.env.BASE_URL}presets/${file}`;

// Preset list (ordered for the scrolling strip). Each `image` is the filename
// in public/presets/ — generated by `node scripts/capture-presets.mjs`, and
// can be regenerated or swapped manually with better screenshots later.
const GALLERY: PresetCardData[] = [
    { preset: PresetName.Brightfield, title: 'Brightfield', category: 'Microscopes', tagline: 'The classic transmitted-light microscope.', accent: '#74b9ff', image: 'brightfield.jpg' },
    { preset: PresetName.EpiFluorescence, title: 'Epi-Fluorescence', category: 'Microscopes', tagline: 'Excitation through the objective, dichroic split.', accent: '#a29bfe', image: 'epi-fluorescence.jpg' },
    { preset: PresetName.TransFluorescence, title: 'Trans. Fluorescence', category: 'Microscopes', tagline: 'Separate excitation and emission paths.', accent: '#ffeaa7', image: 'trans-fluorescence.jpg' },
    { preset: PresetName.OpenSPIM, title: 'OpenSPIM Lightsheet', category: 'Microscopes', tagline: 'Cylindrical lens forms a thin sheet of light.', accent: '#fd79a8', image: 'openspim.jpg' },
    { preset: PresetName.Confocal, title: 'Confocal Scanning', category: 'Microscopes', tagline: 'Descanned PMT + pinhole for optical sectioning.', accent: ACCENT_CYAN, image: 'confocal.jpg' },
    { preset: PresetName.BeamExpander, title: 'Beam Expander', category: 'Optics & Physics', tagline: 'A two-lens Keplerian telescope, the simplest infinity system.', accent: '#fab1a0', image: 'beam-expander.jpg' },
    { preset: PresetName.MZInterferometer, title: 'Mach-Zehnder', category: 'Optics & Physics', tagline: 'Two beam splitters; fringes from path-length differences.', accent: '#7efb62', image: 'mz-interferometer.jpg' },
    { preset: PresetName.OpticalTrap, title: 'Optical Trap', category: 'Optics & Physics', tagline: 'Tightly focused laser holds a high-index bead in place.', accent: '#ff9632', image: 'optical-trap.jpg' },
    { preset: PresetName.LensZoo, title: 'Lens Zoo', category: 'Showcase', tagline: 'Spherical, aspheric, cylindrical, achromatic side-by-side.', accent: '#81ecec', image: 'lens-zoo.jpg' },
    { preset: PresetName.PolarizationZoo, title: 'Polarization Zoo', category: 'Showcase', tagline: 'Waveplates, PBSes, and Jones calculus in one playground.', accent: '#dfa8ff', image: 'polarization-zoo.jpg' },
    { preset: PresetName.CheHangYu2026, title: 'Yu 2026 — Nisam 2x', category: 'Papers', tagline: 'A real high-NA Nisam 2x reflective objective reproduced.', accent: '#ffd1f4', image: 'yu-2026.jpg' },
];

// ── BOMB brand mark ────────────────────────────────────────────────────
const BombBrand: React.FC<{ compact: boolean }> = ({ compact }) => (
    <div style={{
        fontFamily: 'var(--ui-font)',
        color: ACCENT_BLUE,
        textShadow: `0 0 14px rgba(0,127,255,0.85), 0 0 30px rgba(0,127,255,0.45)`,
        userSelect: 'none',
        fontSize: compact ? 22 : 30,
        fontWeight: 700,
        letterSpacing: '-0.3px',
        lineHeight: 1,
    }}>
        Bez's Optics &amp; Microscope Builder
    </div>
);

// ── Tips ticker ────────────────────────────────────────────────────────
const TipTicker: React.FC = () => {
    // Start at a random tip so each refresh feels fresh
    const [index, setIndex] = useState(() => Math.floor(Math.random() * TIPS.length));
    const [visible, setVisible] = useState(true);
    const indexRef = useRef(index);
    indexRef.current = index;

    useEffect(() => {
        const id = window.setInterval(() => {
            // Crossfade: hide → swap → show
            setVisible(false);
            window.setTimeout(() => {
                setIndex(prev => (prev + 1) % TIPS.length);
                setVisible(true);
            }, 350);
        }, 15000);
        return () => window.clearInterval(id);
    }, []);

    return (
        <div style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 10,
            padding: '8px 14px 8px 12px',
            borderRadius: 999,
            border: '1px solid rgba(100,255,218,0.22)',
            background: 'rgba(16, 22, 28, 0.55)',
            backdropFilter: 'blur(6px)',
            maxWidth: '90vw',
        }}>
            <span style={{
                fontSize: 10,
                letterSpacing: 1.4,
                textTransform: 'uppercase',
                fontWeight: 700,
                color: ACCENT_CYAN,
                flexShrink: 0,
            }}>
                Tip
            </span>
            <span
                key={index}
                style={{
                    fontSize: 12.5,
                    color: TEXT_DIM,
                    opacity: visible ? 1 : 0,
                    transition: 'opacity 0.35s ease',
                    lineHeight: 1.4,
                }}
            >
                {TIPS[index]}
            </span>
        </div>
    );
};

// ── Action button (Tutorial / Blank / About) ────────────────────────────
interface ActionCardProps {
    title: string;
    icon: React.ReactNode;
    accent: string;
    onClick?: () => void;
    href?: string;
    primary?: boolean;
    external?: boolean;
}

const ActionCard: React.FC<ActionCardProps> = ({ title, icon, accent, onClick, href, primary, external }) => {
    const [hover, setHover] = useState(false);
    const sharedStyle: React.CSSProperties = {
        position: 'relative',
        appearance: 'none',
        cursor: 'pointer',
        textAlign: 'left',
        textDecoration: 'none',
        padding: '16px 20px',
        borderRadius: 14,
        border: `1px solid ${hover ? accent : 'rgba(148,163,184,0.22)'}`,
        background: primary
            ? `linear-gradient(140deg, rgba(0,127,255,0.18) 0%, rgba(100,255,218,0.14) 100%)`
            : 'rgba(16, 22, 28, 0.72)',
        color: TEXT_PRIMARY,
        fontFamily: 'inherit',
        backdropFilter: 'blur(8px)',
        boxShadow: hover
            ? `0 16px 32px rgba(0,0,0,0.45), 0 0 0 1px ${accent} inset, 0 0 22px ${accent}22`
            : '0 8px 18px rgba(0,0,0,0.32)',
        transform: hover ? 'translateY(-3px)' : 'translateY(0)',
        transition: 'transform 0.22s cubic-bezier(.22,.61,.36,1), box-shadow 0.22s, border-color 0.22s',
        outline: 'none',
        width: '100%',
        display: 'block',
    };
    const inner = (
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div
                style={{
                    width: 36,
                    height: 36,
                    borderRadius: 10,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    background: `${accent}22`,
                    color: accent,
                    flexShrink: 0,
                }}
            >
                {icon}
            </div>
            <div style={{ fontSize: 16, fontWeight: 700, letterSpacing: 0.2 }}>{title}</div>
            {external ? (
                <ExternalLink
                    size={16}
                    color={hover ? accent : TEXT_DIM}
                    style={{
                        marginLeft: 'auto',
                        transition: 'transform 0.22s, color 0.22s',
                        transform: hover ? 'translateX(3px) translateY(-2px)' : 'translateX(0)',
                    }}
                />
            ) : (
                <ChevronRight
                    size={18}
                    color={hover ? accent : TEXT_DIM}
                    style={{
                        marginLeft: 'auto',
                        transition: 'transform 0.22s, color 0.22s',
                        transform: hover ? 'translateX(3px)' : 'translateX(0)',
                    }}
                />
            )}
        </div>
    );
    if (href) {
        return (
            <a
                href={href}
                target={external ? '_blank' : undefined}
                rel={external ? 'noopener noreferrer' : undefined}
                onMouseEnter={() => setHover(true)}
                onMouseLeave={() => setHover(false)}
                style={sharedStyle}
            >
                {inner}
            </a>
        );
    }
    return (
        <button
            type="button"
            onClick={onClick}
            onMouseEnter={() => setHover(true)}
            onMouseLeave={() => setHover(false)}
            style={sharedStyle}
        >
            {inner}
        </button>
    );
};

// ── Preset card on the scrolling strip ─────────────────────────────────
// Card stretches to fill the height of its parent strip; width follows
// aspect ratio so the screenshot itself becomes the card. Title block is
// a translucent band overlaid on the bottom of the image.
const PresetCard: React.FC<{ data: PresetCardData; onOpen: () => void }> = ({ data, onOpen }) => {
    const [hover, setHover] = useState(false);
    return (
        <button
            type="button"
            onClick={onOpen}
            onMouseEnter={() => setHover(true)}
            onMouseLeave={() => setHover(false)}
            style={{
                position: 'relative',
                appearance: 'none',
                cursor: 'pointer',
                textAlign: 'left',
                padding: 0,
                borderRadius: 16,
                border: `1px solid ${hover ? data.accent : 'rgba(148,163,184,0.18)'}`,
                background: '#03060a',
                color: TEXT_PRIMARY,
                fontFamily: 'inherit',
                boxShadow: hover
                    ? `0 22px 48px rgba(0,0,0,0.55), 0 0 36px ${data.accent}33, inset 0 0 0 1px ${data.accent}`
                    : '0 12px 26px rgba(0,0,0,0.4)',
                transform: hover ? 'translateY(-6px)' : 'translateY(0)',
                transition: 'transform 0.22s cubic-bezier(.22,.61,.36,1), box-shadow 0.22s, border-color 0.22s',
                outline: 'none',
                overflow: 'hidden',
                flexShrink: 0,
                // Height comes from the parent strip; width follows aspect.
                // Square so the card is never taller than it is wide — the strip
                // also caps its own height (see PresetStrip) so even a tall
                // portrait window keeps at least three cards visible.
                height: '100%',
                aspectRatio: '1 / 1',
                display: 'block',
            }}
        >
            <img
                src={PRESET_IMAGE_URL(data.image)}
                alt={`${data.title} optical setup`}
                loading="lazy"
                draggable={false}
                style={{
                    position: 'absolute',
                    inset: 0,
                    width: '100%',
                    height: '100%',
                    objectFit: 'cover',
                    objectPosition: 'center',
                    transition: 'transform 0.5s cubic-bezier(.22,.61,.36,1)',
                    transform: hover ? 'scale(1.06)' : 'scale(1)',
                }}
            />
            {/* Top accent strip */}
            <div
                style={{
                    position: 'absolute',
                    top: 0,
                    left: 0,
                    right: 0,
                    height: 3,
                    background: `linear-gradient(90deg, ${data.accent} 0%, transparent 85%)`,
                    opacity: hover ? 1 : 0.7,
                    transition: 'opacity 0.2s',
                }}
            />
            {/* Bottom title band — sits over the image */}
            <div
                style={{
                    position: 'absolute',
                    bottom: 0,
                    left: 0,
                    right: 0,
                    padding: '52px 22px 20px',
                    background: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.5) 32%, rgba(0,0,0,0.94) 100%)',
                    color: TEXT_PRIMARY,
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 4,
                }}
            >
                <div style={{
                    fontSize: 10.5,
                    letterSpacing: 2.0,
                    textTransform: 'uppercase',
                    color: data.accent,
                    fontWeight: 700,
                }}>
                    {data.category}
                </div>
                <div style={{ fontSize: 22, fontWeight: 700, lineHeight: 1.1, letterSpacing: -0.3 }}>{data.title}</div>
            </div>
        </button>
    );
};

// ── Auto-scrolling preset strip ────────────────────────────────────────
// JS-driven scrollLeft so the user keeps a real horizontal scrollbar and can
// drag, wheel, or touch through the gallery. The marquee runs in the
// background and pauses while the user is interacting.
const PresetStrip: React.FC<{ onOpen: (preset: PresetName) => void }> = ({ onOpen }) => {
    // Duplicate the list so the loop wraps seamlessly: when scrollLeft reaches
    // halfway, we jump back by half-width without the user seeing a seam.
    const items = useMemo(() => [...GALLERY, ...GALLERY], []);
    const stripRef = useRef<HTMLDivElement | null>(null);

    useEffect(() => {
        const strip = stripRef.current;
        if (!strip) return;
        let raf = 0;
        let prev = performance.now();
        let pauseUntil = 0;
        const SPEED_PX_PER_SEC = 32;
        const PAUSE_AFTER_INTERACTION_MS = 2200;

        // Any direct user interaction (wheel, drag, touch) pauses auto-scroll
        // briefly so we don't fight the user — then we resume.
        const interact = () => { pauseUntil = performance.now() + PAUSE_AFTER_INTERACTION_MS; };
        strip.addEventListener('wheel', interact, { passive: true });
        strip.addEventListener('pointerdown', interact);
        strip.addEventListener('touchstart', interact, { passive: true });

        const tick = (t: number) => {
            const dt = Math.min(0.1, (t - prev) / 1000);
            prev = t;
            const half = strip.scrollWidth / 2;
            if (t >= pauseUntil) {
                strip.scrollLeft += SPEED_PX_PER_SEC * dt;
            }
            // Seamless wrap: when we pass the halfway mark, snap back. Done
            // every frame so manual scrolling past the seam also wraps.
            if (half > 0) {
                if (strip.scrollLeft >= half) strip.scrollLeft -= half;
                else if (strip.scrollLeft < 0) strip.scrollLeft += half;
            }
            raf = requestAnimationFrame(tick);
        };
        raf = requestAnimationFrame(tick);
        return () => {
            cancelAnimationFrame(raf);
            strip.removeEventListener('wheel', interact);
            strip.removeEventListener('pointerdown', interact);
            strip.removeEventListener('touchstart', interact);
        };
    }, []);

    return (
        <div
            ref={stripRef}
            className="splash-strip"
            style={{
                position: 'relative',
                width: '100%',
                // Strip fills all remaining vertical space, BUT capped so a
                // single square card never exceeds about a third of the
                // viewport width. With cards at aspectRatio 1/1 + gap 22 +
                // paddingInline 24 on each side, this guarantees at least three
                // cards are visible horizontally on any reasonable window
                // (including tall portrait ones).
                flex: 1,
                minHeight: 200,
                maxHeight: 'calc((100vw - 96px) / 3)',
                overflowX: 'auto',
                overflowY: 'hidden',
                scrollbarColor: '#3a4452 transparent',
                scrollbarWidth: 'thin',
            }}
        >
            <div
                style={{
                    display: 'flex',
                    gap: 22,
                    height: '100%',
                    width: 'max-content',
                    // Leave a little vertical breathing room around the cards.
                    paddingInline: 24,
                    paddingBlock: 6,
                }}
            >
                {items.map((data, i) => (
                    <PresetCard key={`${data.preset}-${i}`} data={data} onOpen={() => onOpen(data.preset)} />
                ))}
            </div>
        </div>
    );
};

// ── Ambient backdrop (subtle gradients + reticle) ──────────────────────
const AmbientBackdrop: React.FC = () => {
    return (
        <div
            aria-hidden
            style={{
                position: 'absolute',
                inset: 0,
                overflow: 'hidden',
                pointerEvents: 'none',
                background:
                    'radial-gradient(ellipse at 20% 10%, rgba(0,127,255,0.12) 0%, transparent 55%),' +
                    'radial-gradient(ellipse at 80% 90%, rgba(100,255,218,0.10) 0%, transparent 55%),' +
                    'radial-gradient(circle at center, #0a0e17 0%, #000000 100%)',
            }}
        >
            <svg
                viewBox="0 0 1000 1000"
                preserveAspectRatio="xMidYMid slice"
                style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', opacity: 0.16 }}
            >
                <defs>
                    <radialGradient id="splash-reticle-glow" cx="50%" cy="50%" r="50%">
                        <stop offset="0%" stopColor="rgba(100,255,218,0.45)" />
                        <stop offset="60%" stopColor="rgba(100,255,218,0.06)" />
                        <stop offset="100%" stopColor="rgba(100,255,218,0)" />
                    </radialGradient>
                </defs>
                <circle cx="500" cy="500" r="420" fill="none" stroke="rgba(100,255,218,0.22)" strokeWidth="1" />
                <circle cx="500" cy="500" r="320" fill="none" stroke="rgba(100,255,218,0.16)" strokeWidth="1" />
                <circle cx="500" cy="500" r="220" fill="none" stroke="rgba(100,255,218,0.10)" strokeWidth="1" />
                <circle cx="500" cy="500" r="500" fill="url(#splash-reticle-glow)" />
                <line x1="0" y1="500" x2="1000" y2="500" stroke="rgba(100,255,218,0.12)" strokeWidth="1" strokeDasharray="2 8" />
                <line x1="500" y1="0" x2="500" y2="1000" stroke="rgba(100,255,218,0.12)" strokeWidth="1" strokeDasharray="2 8" />
            </svg>
        </div>
    );
};

// ── Splash root ─────────────────────────────────────────────────────────
export const Splash: React.FC = () => {
    const [, setAppRoute] = useAtom(appRouteAtom);
    const [, loadPreset] = useAtom(loadPresetAtom);
    const isMobile = useIsMobile();

    const startEditor = (preset: PresetName) => {
        loadPreset(preset);
        setAppRoute('editor');
    };

    return (
        <div style={{
            position: 'fixed',
            inset: 0,
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
            fontFamily: 'var(--ui-font)',
            color: TEXT_PRIMARY,
            zIndex: 100,
            background: '#000',
        }}>
            <AmbientBackdrop />
            <div style={{
                position: 'relative',
                zIndex: 1,
                width: '100%',
                height: '100%',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'stretch',
                paddingTop: isMobile ? 18 : 24,
                paddingBottom: isMobile ? 14 : 18,
                gap: isMobile ? 14 : 16,
                overflow: 'hidden',
            }}>
                {/* Hero — compact at top */}
                <div style={{
                    width: '100%',
                    maxWidth: 1100,
                    margin: '0 auto',
                    padding: isMobile ? '0 18px' : '0 28px',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    textAlign: 'center',
                    gap: isMobile ? 8 : 10,
                    flexShrink: 0,
                }}>
                    <BombBrand compact={isMobile} />
                    <h1 style={{
                        fontSize: isMobile ? 28 : 44,
                        lineHeight: 1.05,
                        fontWeight: 700,
                        letterSpacing: -0.8,
                        margin: 0,
                        background: `linear-gradient(180deg, #ffffff 0%, #b8c8da 100%)`,
                        WebkitBackgroundClip: 'text',
                        WebkitTextFillColor: 'transparent',
                        backgroundClip: 'text',
                    }}>
                        Learn optics. Lay out instruments.
                    </h1>
                </div>

                {/* Action cards — tight row */}
                <div style={{
                    width: '100%',
                    maxWidth: 1100,
                    margin: '0 auto',
                    padding: isMobile ? '0 18px' : '0 28px',
                    display: 'grid',
                    gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)',
                    gap: 12,
                    flexShrink: 0,
                }}>
                    <ActionCard
                        title="Start Tutorial"
                        icon={<GraduationCap size={20} strokeWidth={1.9} />}
                        accent={ACCENT_CYAN}
                        primary
                        onClick={() => startEditor(PresetName.Tutorial)}
                    />
                    <ActionCard
                        title="Blank Workspace"
                        icon={<MousePointer2 size={20} strokeWidth={1.9} />}
                        accent={ACCENT_BLUE}
                        onClick={() => startEditor(PresetName.Blank)}
                    />
                    <ActionCard
                        title="About"
                        icon={<Info size={20} strokeWidth={1.9} />}
                        accent="#ffd1f4"
                        href="https://bezialemma.com/microscope_about"
                        external
                    />
                </div>

                {/* Preset gallery — fills all remaining vertical space */}
                <div style={{
                    width: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    flex: 1,
                    minHeight: 0,
                }}>
                    <PresetStrip onOpen={startEditor} />
                </div>

                {/* Tip ticker pinned to the bottom */}
                <div style={{ display: 'flex', justifyContent: 'center', flexShrink: 0, padding: '0 18px' }}>
                    <TipTicker />
                </div>
            </div>
        </div>
    );
};
